### ISSUE TITLE
Regression Modules - All

### ISSUE THREAD

**Issue by MissAle17** [learn-co-curriculum/gradient-descent#1]
I am unable to see any of the graphs in the regression lessons/labs.  There is a very long error message that starts as follows:

ValueErrorTraceback (most recent call last)
<ipython-input-12-f0470a163cad> in <module>()
      6 
      7 cost_curve_trace = trace_values(b_values, rss_errors, mode="line")
----> 8 plot([cost_curve_trace])

**Comment by runsun-edu** [comment]
Not sure if you encountered the same errors as I did (after all it's been 4 months since you raised this issue). 
 What I see: the teaching materials use `mode='line'` in traces that are to be fed to **plot()** at places where the **plotly** lib requires `mode='lines'`. This error occurs more than once through out the regression lessons.

**Comment by LoreDirick** [comment]
correct, fixing it now, thanks!
